export const LIBRARY_KEY = 'math_deck_library'

export const SUBJECTS = {
  real_analysis: {
    label: 'Real Analysis',
    examples: [
      'Cauchy Sequences',
      'Heine-Borel Theorem',
      'Uniform Continuity',
      'Riemann Integrability',
      'Monotone Convergence Theorem',
      'Open and Closed Sets',
      'Compactness',
      'lim sup and lim inf',
    ],
    systemPromptHint: 'Emphasize epsilon-delta rigor. Use Ross-style notation. Ground every definition in concrete sequence or metric space examples before abstraction. Cite section references like §10.8.',
  },
  calculus: {
    label: 'Calculus',
    examples: [
      'Chain Rule',
      'Fundamental Theorem of Calculus',
      'L\'Hôpital\'s Rule',
      'Taylor Series',
      'Integration by Parts',
      'Implicit Differentiation',
      'Related Rates',
      'Optimization Problems',
    ],
    systemPromptHint: 'Start with geometric intuition (slopes, areas, rates). Use visual descriptions of curves and tangent lines. Connect derivatives and integrals to real-world rates of change. Limit formalism to where it truly helps.',
  },
  linear_algebra: {
    label: 'Linear Algebra',
    examples: [
      'Eigenvalues and Eigenvectors',
      'Singular Value Decomposition',
      'Linear Transformations',
      'Orthogonality and Gram-Schmidt',
      'Determinants',
      'Null Space and Column Space',
      'Diagonalization',
      'Positive Definite Matrices',
    ],
    systemPromptHint: 'Emphasize geometric meaning of transformations — what do matrices *do* to vectors? Use concrete 2D and 3D examples before generalizing. Connect algebra to geometry constantly.',
  },
  topology: {
    label: 'Topology',
    examples: [
      'Open and Closed Sets',
      'Compactness',
      'Connectedness',
      'Homeomorphisms',
      'Metric Spaces',
      'Continuity in Topology',
      'Product Topology',
      'Quotient Spaces',
    ],
    systemPromptHint: 'Build intuition with concrete metric spaces and subsets of ℝⁿ before abstracting. Use rubber-sheet geometry analogies. Emphasize which properties are topological invariants and why that matters.',
  },
  abstract_algebra: {
    label: 'Abstract Algebra',
    examples: [
      'Group Homomorphisms',
      'Lagrange\'s Theorem',
      'Normal Subgroups and Quotient Groups',
      'Ring Ideals',
      'Field Extensions',
      'Sylow Theorems',
      'Galois Theory',
      'Isomorphism Theorems',
    ],
    systemPromptHint: 'Start each concept with a concrete example (integers, symmetric groups, polynomials) before the abstract definition. Use tables and diagrams for small groups. Emphasize the "why" behind each structural constraint.',
  },
  optimization: {
    label: 'Optimization',
    examples: [
      'Convex Functions',
      'KKT Conditions',
      'Gradient Descent',
      'Lagrange Multipliers',
      'Linear Programming Duality',
      'Conjugate Gradient Method',
      'Stochastic Gradient Descent',
      'Newton\'s Method',
    ],
    systemPromptHint: 'Motivate each method with a concrete optimization problem. Visualize loss landscapes. Connect first-order and second-order conditions geometrically. Emphasize practical convergence rates and when each method applies.',
  },
  probability: {
    label: 'Probability Theory',
    examples: [
      'Law of Large Numbers',
      'Central Limit Theorem',
      'Conditional Expectation',
      'Markov Chains',
      'Moment Generating Functions',
      'Convergence of Random Variables',
      'Bayes\' Theorem',
      'Poisson Processes',
    ],
    systemPromptHint: 'Always ground probability in a concrete sample space first. Use simulation intuition — "if you ran this experiment a million times…". Distinguish between almost-sure, in-probability, and in-distribution convergence clearly.',
  },
  differential_equations: {
    label: 'Differential Equations',
    examples: [
      'Separation of Variables',
      'Linear Systems and Eigenvalues',
      'Phase Plane Analysis',
      'Existence and Uniqueness',
      'Fourier Series',
      'Laplace Transforms',
      'Stability of Equilibria',
      'Power Series Solutions',
    ],
    systemPromptHint: 'Start with a physical or biological model (population, heat, oscillation) that motivates the equation. Draw direction fields and phase portraits. Emphasize qualitative behavior alongside algebraic solution methods.',
  },
  complex_analysis: {
    label: 'Complex Analysis',
    examples: [
      'Cauchy-Riemann Equations',
      'Cauchy\'s Integral Formula',
      'Residue Theorem',
      'Analytic Functions',
      'Conformal Mappings',
      'Laurent Series',
      'Morera\'s Theorem',
      'Riemann Mapping Theorem',
    ],
    systemPromptHint: 'Visualize everything in the complex plane. Use geometric interpretations of analytic functions as angle-preserving maps. Connect real and imaginary parts via harmonicity. Show how contour integration unlocks otherwise-intractable real integrals.',
  },
  numerical_analysis: {
    label: 'Numerical Analysis',
    examples: [
      'Newton\'s Method',
      'Gaussian Elimination',
      'Runge-Kutta Methods',
      'Interpolation and Splines',
      'Numerical Integration (Quadrature)',
      'Finite Difference Methods',
      'Condition Number and Stability',
      'QR Decomposition',
    ],
    systemPromptHint: 'Always pair an algorithm with its error analysis and convergence rate. Use concrete floating-point examples to motivate why numerical stability matters. Show worked computations by hand for small cases before discussing implementation.',
  },
  game_theory: {
    label: 'Game Theory',
    examples: [
      'Nash Equilibrium',
      'Prisoner\'s Dilemma',
      'Mixed Strategies',
      'Dominant Strategies',
      'Backward Induction',
      'Bayesian Games',
      'Cooperative Games and Shapley Value',
      'Zero-Sum Games and Minimax',
    ],
    systemPromptHint: 'Open with a concrete strategic scenario (2-player normal-form game, payoff matrix). Use specific numeric examples to compute equilibria by hand. Emphasize when rational individual behavior leads to collectively suboptimal outcomes.',
  },
  networks: {
    label: 'Networks',
    examples: [
      'Network Flow and Max-Flow Min-Cut',
      'Centrality Measures',
      'Small-World Networks',
      'Scale-Free Networks',
      'Shortest Path Algorithms',
      'Community Detection',
      'Percolation Theory',
      'Random Graph Models',
    ],
    systemPromptHint: 'Draw small example networks to ground every definition. Connect structural properties (degree distribution, clustering) to real-world phenomena (internet, social networks, epidemics). Use Erdős-Rényi as the baseline random model before introducing power laws.',
  },
  graph_theory: {
    label: 'Graph Theory',
    examples: [
      'Trees and Spanning Trees',
      'Eulerian and Hamiltonian Paths',
      'Graph Coloring',
      'Planar Graphs and Euler\'s Formula',
      'Bipartite Matching',
      'Connectivity and Cuts',
      'Ramsey Theory',
      'Spectral Graph Theory',
    ],
    systemPromptHint: 'Always draw a small example graph (5–8 vertices) before stating a theorem. Use combinatorial counting arguments alongside algebraic ones. Connect theorems to algorithmic applications — e.g. coloring to scheduling, matching to assignment problems.',
  },
  algorithms: {
    label: 'Algorithms',
    examples: [
      'Divide and Conquer',
      'Dynamic Programming',
      'Greedy Algorithms',
      'Depth-First and Breadth-First Search',
      'Sorting: Merge Sort and Quick Sort',
      'P vs NP',
      'Amortized Analysis',
      'Network Flow Algorithms',
    ],
    systemPromptHint: 'Trace through a concrete small input by hand before analyzing complexity. Use recurrence relations for divide-and-conquer. Draw recursion trees and DP tables. Distinguish worst-case, average-case, and amortized analysis clearly.',
  },
  number_theory: {
    label: 'Number Theory',
    examples: [
      'Modular Arithmetic',
      'Fermat\'s Little Theorem',
      'Chinese Remainder Theorem',
      'Quadratic Residues',
      'RSA Cryptography',
      'Continued Fractions',
      'Diophantine Equations',
      'Prime Number Theorem',
    ],
    systemPromptHint: 'Use small numeric examples to reveal the pattern before stating the theorem. Show how elementary number theory underlies modern cryptography. Emphasize the interplay between divisibility, congruences, and the structure of ℤ/nℤ.',
  },
  differential_geometry: {
    label: 'Differential Geometry',
    examples: [
      'Curves and Curvature',
      'Surfaces and the First Fundamental Form',
      'Gaussian Curvature',
      'Geodesics',
      'Gauss-Bonnet Theorem',
      'Connections and Parallel Transport',
      'Manifolds',
      'Riemannian Metric',
    ],
    systemPromptHint: 'Ground everything in familiar surfaces: sphere, torus, saddle. Use the intrinsic vs. extrinsic distinction early. Visualize parallel transport with concrete paths on a sphere. Connect curvature to the behavior of geodesics and the topology of the surface.',
  },
  computability: {
    label: 'Computability Theory',
    examples: [
      'Turing Machines',
      'The Halting Problem',
      'Church-Turing Thesis',
      'Decidability and Undecidability',
      'Rice\'s Theorem',
      'Reductions',
      'Recursive and Recursively Enumerable Sets',
      'Gödel\'s Incompleteness Theorems',
    ],
    systemPromptHint: 'Use thought experiments and informal English descriptions of machines before writing formal encodings. Make the diagonalization argument visceral — self-referential paradoxes are the heart of this subject. Connect undecidability to everyday limitations of software.',
  },
  set_theory: {
    label: 'Set Theory',
    examples: [
      'Axiom of Choice',
      'Cardinality and Countability',
      'Cantor\'s Theorem',
      'Ordinals and Cardinals',
      'Zorn\'s Lemma',
      'Continuum Hypothesis',
      'Well-Ordering Theorem',
      'Transfinite Induction',
    ],
    systemPromptHint: 'Build intuition for infinite sizes with concrete bijections (ℕ ↔ ℤ ↔ ℚ, then Cantor\'s diagonal argument). Make ordinal arithmetic tangible with small examples. Emphasize how the Axiom of Choice is equivalent to seemingly unrelated statements.',
  },
  fourier_analysis: {
    label: 'Fourier Analysis',
    examples: [
      'Fourier Series',
      'Fourier Transform',
      'Convolution Theorem',
      'Parseval\'s Theorem',
      'Discrete Fourier Transform',
      'Sampling and Nyquist Theorem',
      'Heat Equation via Fourier',
      'Windowed Fourier and Wavelets',
    ],
    systemPromptHint: 'Use sound and signal processing as the primary physical intuition — frequencies, harmonics, filtering. Show the Fourier series converging on a square wave visually. Connect the continuous and discrete transforms explicitly. Emphasize the uncertainty principle as a deep duality.',
  },
}
